spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_user_db
    username: postgres
    password: postgres

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  test:
    database:
      replace: none

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9090

app:
  kafka:
    topic: user.events

keycloak:
  admin:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:nexus}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:nexus-user-service}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

outbox:
  poller:
    delay: 3000