spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_user_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  test:
    database:
      replace: none

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topic: user.events

outbox:
  poller:
    delay: 3000