server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nexus_user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  test:
    database:
      replace: none

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  kafka:
    topic: user.events

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

keycloak:
  admin:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:nexus}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:nexus-user-service}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

outbox:
  poller:
    delay: 3000